---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress-server
  become_user: root
  become: yes
  become_method: sudo
 
  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
